volumes:
  timescaledb: 
    external: false

services:
  timescaledb:
    image: timescale/timescaledb-ha:pg18
    volumes:
      - timescaledb:/home/postgres/pgdata/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=timescaledb_test
    ports:
      - 5432:5432